import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      style={{
        fontSize: "62.5%",
      }}
    >
      <body
        className={inter.className}
        style={{
          fontSize: "2.4rem",
        }}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
